language: scala

jdk: openjdk8

scala:
   - 2.12.4

services:
   - mysql
   - postgresql

before_install:
   - mysql -e "CREATE DATABASE films;"
   - mysql -e "USE films; CREATE TABLE films (id int, name varchar(48), year int, country varchar(48), director varchar(48));"
   - mysql -e "USE films; INSERT INTO films (id, name, year, country, director) VALUES (8, 'Tenet', 2020, 'UK', 'Christopher Nolan');"
   - mysql -e "USE films; INSERT INTO films (id, name, year, country, director) VALUES (9, 'Batman Begins', 2005, 'USA', 'Christopher Nolan');"

before_script:
   - psql -c "CREATE DATABASE films;" -U postgres
   - psql -c "USE films; CREATE TABLE films (id int, name varchar(48), year int, country varchar(48), director varchar(48));" -U postgres
   - psql -c "USE films; INSERT INTO films (id, name, year, country, director) VALUES (8, 'Tenet', 2020, 'UK', 'Christopher Nolan');" -U postgres
   - psql -c "USE films; INSERT INTO films (id, name, year, country, director) VALUES (9, 'Batman Begins', 2005, 'USA', 'Christopher Nolan');" -U postgres