name: Scala CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Set up MySQL
      run: sudo service mysql start  &&
            mysql -e "CREATE DATABASE films;" -u root -proot &&
            mysql -e "USE films; CREATE TABLE films (id int, name varchar(48), year int, country varchar(48), director varchar(48));" -u root -proot &&
            mysql -e "USE films; INSERT INTO films (id, name, year, country, director) VALUES (8, 'Tenet', 2020, 'UK', 'Christopher Nolan');" -u root -proot &&
            mysql -e "USE films; INSERT INTO films (id, name, year, country, director) VALUES (9, 'Batman Begins', 2005, 'USA', 'Christopher Nolan');" -u root -proot
    - name: Set up PostgreSQL
      run:  sudo systemctl restart postgresql &&
            psql -c "CREATE DATABASE films;" -U postgres -h 127.0.0.1 &&
            psql -c "CREATE TABLE films (id int, name varchar(48), year int, country varchar(48), director varchar(48));" films -U postgres -h 127.0.0.1 &&
            psql -c "INSERT INTO films (id, name, year, country, director) VALUES (8, 'Tenet', 2020, 'UK', 'Christopher Nolan');" films -U postgres -h 127.0.0.1 &&
            psql -c "INSERT INTO films (id, name, year, country, director) VALUES (9, 'Batman Begins', 2005, 'USA', 'Christopher Nolan');" films -U postgres -h 127.0.0.1
    - name: Run tests
      run: sbt test
